# Default state for all rules
default: true

# MD013/line-length - Line length
MD013: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false
