# Default state for all rules
default: true

# MD007/ul-indent - Unordered list indentation
MD007:
  indent: 4

# MD013/line-length - Line length
MD013: false

# MD032/blanks-around-lists - Lists should be surrounded by blank lines
MD032: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
MD036: false
