# terrascan configuration file https://github.com/accurics/terrascan/blob/master/config/terrascan.toml

# scan and skip rules configuration
[rules]
    # scan rules (list of rules to scan, adding rules here will override rules in the policy path)
    # scan-rules = [
    #     "AWS.S3Bucket.DS.High.1043",
    #     "AWS.S3Bucket.IAM.High.0370"
    # ]

    # skip rules (list of rules to skip)
    skip-rules = []
