name: Dialogflow CX Webhook Python
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/dialogflow-cx-webhook-python.yaml
      - dialogflow-cx-webhook-python/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/dialogflow-cx-webhook-python.yaml
      - dialogflow-cx-webhook-python/**
jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dialogflow-cx-webhook-python
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/checkout@v3
      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          python main_test.py
